spring:
  flyway:
    baseline-on-migrate: true
    check-location: false
    locations: db/migration
    schemas: public
    enabled: true

app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/demodb
    username: annguyen
    password: annguyen
    pool-size: 30

